server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.80.128
    username: leyou
    password: 123456
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://222.24.14.51:10086/eureka