server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.80.128:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.80.128
    username: leyou
    password: 123456
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://222.24.14.51:10086/eureka
    registry-fetch-interval-seconds: 5
ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
