server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: mysql
  rabbitmq:
    host: 192.168.80.128
    username: leyou
    password: 123456
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://222.24.14.51:10086/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
  eureka:
    enabled: true